### ISSUE TITLE
Improvement: No-Route Elements with HasErrorParameter are not detected

### ISSUE THREAD

**Issue by eiswind** [mvysny/karibu-testing#10]
As in the docs, Components with HasErrorParameter should not have any Routes.
It would be really nice if they were detected in the Mock Setup.

For e.g. 

@ParentLayout(MainLayout::class)
class AccessDeniedView : VerticalLayout(), HasErrorParameter<AccessDeniedException> {

**Comment by eiswind** [comment]
I did not see the addErrorRoutes! and as I do not have any idea for the detection I guess I will live with that solution for today. Thanks for helping me out!

**Comment by mvysny** [comment]
Actually I have find this handy library which performs all kinds of neat classpath scanning: https://github.com/classgraph/classgraph

**Comment by mvysny** [comment]
Fixed in Karibu-Testing 1.0.2
