### ISSUE TITLE
Support for LitRenderer in _getFormattedRow

### ISSUE THREAD

**Issue by eiswind** [mvysny/karibu-testing#104]
WIth my migration to Vaadin 23 I changed the TemplateRenderers to LitRenderer. Now some tests are failing, because _getFormattedRow has no support for that,

I think this could be implemented without big effort. If you agree I can provide a PR for that.

https://github.com/mvysny/karibu-testing/blob/bfb476ae841244ddaa5df9dad1db04520f94fb37/karibu-testing-v10/src/main/kotlin/com/github/mvysny/kaributesting/v10/Renderers.kt#L23-L39

**Comment by mvysny** [comment]
Absolutely, that would be awesome, thank you :+1:

**Comment by mvysny** [comment]
Fixed by https://github.com/mvysny/karibu-testing/pull/106
