### ISSUE TITLE
Set a value on a Select Component

### ISSUE THREAD

**Issue by TartineDePain35** [mvysny/karibu-testing#108]
Hi, 

Got a issue there, 
A Select component with two option, that build the rest of the page differently according to user choice. 

Wanna set the value of the select in a test suite, but I can't find how to do this. 
ComboBoxKt.getSuggestions() work's fine to get the Select suggestions, but seems like ComboBox.setUserInput() or ComboBoxKt.setUserInput() doesn't work to set the Select Component value. Is there a way to do this ? 

Thanks. :)

**Comment by mvysny** [comment]
Well Select doesn't support user typing in text, so the `setUserInput()` is unavailable for Select. A call to `_setValue(select, item)` should work instead.

**Comment by TartineDePain35** [comment]
Thanks for the answer, 

A _setValue(select, item) throw a NullpointerException, it seem that it cast the position of the vaadin-item value but not the value. When i try : 
_setValue(select, string) i got a null pointer.
When i try : 
_setValue(select, integer) i got ClassCast exception. 

Pretty stuck right now with this select component i wanna test. :/

**Comment by mvysny** [comment]
Can you post the stacktrace of the NPE?

**Comment by TartineDePain35** [comment]
Hi Martin, 
We finaly resolve this NPE. It wasn't Karibus fault. :) 
I just forgot to set an item. 
Thanks fot the time spend on this "non issue". lol
