### ISSUE TITLE
MenuItem doesn't support the checkable property

### ISSUE THREAD

**Issue by nbabb** [mvysny/karibu-testing#110]
I have a ContextMenu where the MenuItem's are specified as isCheckable = true.  When I click them using this API call

`fun HasMenuItems._clickItemWithCaption(caption: String) ` the menu item is selected, however the MenuItem.isChecked property does not toggle as expected.

I am aware of this issue (https://github.com/mvysny/karibu-testing/issues/20) with ContextMenu testing and worked around that by maintaining a reference to the ContextMenu from an associated Button subclass that I use as it's trigger.  This seems to be a separate issue with ContextMenu support of checked tracking.

**Comment by mvysny** [comment]
Let me investigate please. Maybe Karibu can detect that a menu-item is checkable, and emulate vaadin behavior by toggling the "checked" state.
