### ISSUE TITLE
PreserveOnRefresh annotation is not handled correctly in tests

### ISSUE THREAD

**Issue by willemv** [mvysny/karibu-testing#118]
When you have a view with the `@PreserveOnRefresh` annotation, the view should survive a page reload but be reparented to a new UI.

The real VaadinServlet handles this in its `AbstractNavigationStateRenderer` (see its `isPreserveOnRefreshTarget` method), but when you call karibu's `MockPage#reload` this code is not triggered.

**Comment by mvysny** [comment]
Hi Willem, thank you for letting me know. You're right, I've reproduced the bug. Now the question is, how to fix it :-D

**Comment by mvysny** [comment]
Vaadin actually tries to remember the previous instances of the navigation chain, but needs ExtendedClientDetails to do so. Karibu-Testing doesn't mock that part of Vaadin, the ui.getPage().retrieveExtendedClientDetails() never calls the closure and thus the preserve-on-refresh storage never gets initialized. Let me work on that.

**Comment by mvysny** [comment]
Added support for `ExtendedClientDetails` which also adds support for `@PreserveOnRefresh`. Proverbial two birds one stone ;)

Fix will be present in Karibu-Testing 1.3.17

**Comment by willemv** [comment]
Thanks @mvysny, everything is working now!
