### ISSUE TITLE
Vaadin 7 Support

### ISSUE THREAD

**Issue by jorginius** [mvysny/karibu-testing#120]
Hello,

I am trying to port a very old Vaadin app with zero tests. Is it possible to use Karibu Testing with Vaadin 7? The documentation talks about Vaadin 8 but on the [Old Vaadin Forum](https://vaadin.com/forum/thread/497950/unit-testing-vaadin) @mvysny said (Emphasis mine 😄):

> The Karibu Testing framework may be exactly what you're looking for. It supports both Vaadin 8 and Vaadin 10; **adding Vaadin 7 support is very easy**. https://github.com/mvysny/karibu-testing 

Any hints?

Thank you

**Comment by mvysny** [comment]
Hi, Vaadin 7 and Vaadin 8 frameworks are very similar (the initialization procedure is similar), therefore Karibu mocking code should work with vaadin 7 as well. You can try to change `vaadin8_version=7.x.x` in `gradle.properties` then rebuild karibu, to see whether karibu would work out of the box; if not then it might require simple fixes here and there.

**Comment by jorginius** [comment]
Thanks, i will try.

I think it's not worth releasing for Vaadin 7 at this point. I will copy your v8 code in the project directly while I'm working on the port. If I find any problem, I will try to make pull request.

There would be no licensing problem, right? (It is a closed-source software)

**Comment by mvysny** [comment]
> There would be no licensing problem, right? (It is a closed-source software)

No problem there. Karibu uses a permissive Apache license which allows code usage in closed-source projects. Please feel free to use the code in any way you need 👍

**Comment by mvysny** [comment]
Closing as WON'T FIX as discussed above.
