### ISSUE TITLE
ContextMenu has to be clicked twice to uncheck

### ISSUE THREAD

**Issue by simasch** [mvysny/karibu-testing#126]
I have a ContextMenu with items created like this:

    MenuItem menuItem = addItem(label, e -> {
        boolean checked = e.getSource().isChecked();
        column.setVisible(checked);
    });
    menuItem.setCheckable(true);
    menuItem.setChecked(true);

Now I write a test:

    ContextMenuKt._clickItemWithCaption(contextMenu, "Vertrag");

But then checked is still true. I hae to call `_clickItemWithCaption` twice to have it unchecked.

**Comment by mvysny** [comment]
Hi, excellent catch, thank you for letting me know. I have reproduced the issue.

**Comment by mvysny** [comment]
Fixed in Karibu-Testing 1.3.19
