### ISSUE TITLE
Error when using @RouteScope in components

### ISSUE THREAD

**Issue by brunovianarezende** [mvysny/karibu-testing#128]
I have a component annotated with @RouteScope and when I try to init the app in the test, I get the error:

```
Caused by: java.lang.IllegalStateException: No WebApplicationContext found: no ContextLoaderListener registered?
	at org.springframework.web.context.support.WebApplicationContextUtils.getRequiredWebApplicationContext(WebApplicationContextUtils.java:85)
	at com.vaadin.flow.spring.scopes.VaadinRouteScope$RouteBeanStore.getContext(VaadinRouteScope.java:372)
```

This is the code in my test class:

```
  private static final Routes routes = new Routes().autoDiscoverViews("the.package");

  @Autowired
  private ApplicationContext ctx;

  @BeforeEach
  public void mockVaadin() {
    final Function0<UI> uiFactory = UI::new;
    final SpringServlet servlet = new MockSpringServlet(routes, ctx, uiFactory);
    MockVaadin.setup(uiFactory, servlet);
  }
```

To fix this error, I've changed the mockVaadin() function to:

```
  @BeforeEach
  public void mockVaadin() {
    final Function0<UI> uiFactory = UI::new;
    final SpringServlet servlet = new MockSpringServlet(routes, ctx, uiFactory);
    MockVaadin.setup(uiFactory, servlet);
    servlet.getServletContext()
        .setAttribute(WebApplicationContext.ROOT_WEB_APPLICATION_CONTEXT_ATTRIBUTE, ctx);
  }
```

I think we should do this setup somewhere in karibu. My first idea is to add the code that sets the WebAplicationContext inside `MockVaadin.setup`. What do you think?

**Comment by mvysny** [comment]
Hi Bruno, thanks for letting me know! Actually this should have been performed in `MockSpringServlet.init()` at line 58, which should have been called by `MockVaadin.setup()` at line 88. I've tried to debug Karibu internal tests and the init() function seems to be called; however in your case for some reason it's not called. Could you please try to debug through `MockVaadin.setup()` a bit, to see what's going on?

**Comment by brunovianarezende** [comment]
Hi Martin, I will try with karibu-testing 1.3.18 and check if it still happening. If it is, I will debug and see what I can come up with.

**Comment by brunovianarezende** [comment]
In 1.3.18 the WebApplicationContext is being, I see this was added in 1.3.13: https://github.com/mvysny/karibu-testing/commit/fd2bd453eb698ec289c60c91426078edc1bc396d. With version 1.3.18 I get another error. I will try to debug it and I will open another ticket if I find it isn't anything specific to my code.
