### ISSUE TITLE
Support for MultiSelectComboBox 

### ISSUE THREAD

**Issue by satorstefan** [mvysny/karibu-testing#134]
Hello Martin,

Will karibu support MultiSelectComboBox?
Vaadin version 23.2.2.

![image](https://user-images.githubusercontent.com/25597168/193420736-2bfe8b55-3359-44dd-b607-3ac618e0fb75.png)

Best regards
Stefan

**Comment by mvysny** [comment]
Hi Stefan, that's definitely something we should support. Let me take a look :+1:

**Comment by mvysny** [comment]
Implemented in Karibu-Testing 1.3.21

**Comment by satorstefan** [comment]
Ok, I will wait for the release:
https://mvnrepository.com/artifact/com.github.mvysny.kaributesting/karibu-testing-v10
