### ISSUE TITLE
MultiSelectComboBox Karibu 1.3.21

### ISSUE THREAD

**Issue by satorstefan** [mvysny/karibu-testing#145]
Hello Martin,
 
Support for MultiSelectComboBox(Since Karibu-Testing 1.3.21)
Should be available.
 
But yet despite using version <karibu.version>1.3.23</karibu.version>
I cannot find that static methode.
 
Could you please check?

**Comment by mvysny** [comment]
Hi, according to https://github.com/mvysny/karibu-testing/tree/master/karibu-testing-v10#support-for-multiselectcombobox you need to pull in the `karibu-testing-v23` dependency. Have you tried that please?

**Comment by satorstefan** [comment]
This should be ok, right?
![image](https://user-images.githubusercontent.com/25597168/228571305-dcbe12a8-8f48-4a5b-9afe-08cff8b784db.png)

**Comment by satorstefan** [comment]
Or do you mean this?
![image](https://user-images.githubusercontent.com/25597168/228572266-ef12d203-0ea0-4ffa-9901-5447e3d7ae5c.png)

**Comment by satorstefan** [comment]
Should I switch to this?
![image](https://user-images.githubusercontent.com/25597168/228572711-d3521031-451a-4421-ad30-574601df2ede.png)

**Comment by satorstefan** [comment]
Then this dependency is missing:
![image](https://user-images.githubusercontent.com/25597168/228575010-14caa12e-0968-4680-a38b-91bafca5392d.png)

**Comment by satorstefan** [comment]
Now I understand this comment "Make sure to depend on karibu-testing-v23 to gain access to these functions."

**Comment by satorstefan** [comment]
And there is even another comment "For Vaadin 23, use karibu-testing-v23 instead (starting with Karibu-Testing 1.3.16)."

Ok, I thought just <karibu.version>1.3.23</karibu.version> would be enough to configure everything.

So the question then is how to use karibu-testing-v23 with spring?

**Comment by mvysny** [comment]
Hi, you're right, the documentation should have been clearer. I've improved the readme and added more information here: https://github.com/mvysny/karibu-testing/tree/master/karibu-testing-v10#using-karibu-testing-with-spring

Please let me know whether it makes sense. In short, if you need both Vaadin 23 integration and Spring integration, simply depend on both `karibu-testing-v10-spring` and `karibu-testing-v23` Maven modules.

**Comment by satorstefan** [comment]
Hello Martin,
now it makes sense and works.

Thanks alot!
