### ISSUE TITLE
How to check that a column is not present in a grid

### ISSUE THREAD

**Issue by satorstefan** [mvysny/karibu-testing#150]
I want to check that a user will not see some columns of a grid.

The columns have keys.

Maybe a methode like:
assertColumnNotVisible(String key)
would be helpful?

**Comment by mvysny** [comment]
Hi, thank you for letting me know!

Perhaps something like `assertFalse(GridKt._getColumnByKey(key).isVisible())` would work equally well - it would provide a proper error message if the column with such a key doesn't exist.

Basically, I'm trying to avoid the API duplication. For example, if we would to have `assertColumnNotVisible(String key)`, then we should also have `assertColumnSortable()`, `assertColumnIsFrozen()`, `assertColumnIsNotFrozen(String key)` and a function for every `Grid.Column` property, which looks like a lot of existing API duplication.

I propose to instead document the `assertColumnNotVisible()` solution in the README. Would that work for you?

**Comment by mvysny** [comment]
Documentation added: https://github.com/mvysny/karibu-testing/tree/master/karibu-testing-v10#grid-columns

**Comment by satorstefan** [comment]
Also I think there is a typo in the documentation now. This is not the right code snippet:
assertFalse(GridKt._getColumnByKey(grid, "delete"));

**Comment by satorstefan** [comment]
This seems to work:

     assertThrows(AssertionError.class, () -> {
            GridKt._getColumnByKey(getGrid(), "delete");
        });

**Comment by mvysny** [comment]
You need to replace "delete" with the appropriate key of your Grid's Column.

**Comment by satorstefan** [comment]
GridKt._getColumnByKey(getGrid(), SafeguardTable.COLUMN_ACTION);

also leads to:

java.lang.AssertionError: Grid[dataprovider='CallbackDataProvider', @multi-sort-priority='prepend', @theme='no-row-borders compact no-border column-dividers second-grid-theme']: No such column with key 'action'; available columns: [name, typ, factor, changedAt]


This works. So maybe you should update the documentation again?

        assertThrows(AssertionError.class, () -> {
            GridKt._getColumnByKey(getGrid(), SafeguardTable.COLUMN_ACTION);
        });

**Comment by mvysny** [comment]
Please try `GridKt._getColumnByKey(getGrid(), "changedAt");` or some other column that exists on the grid.

**Comment by satorstefan** [comment]
That works, but I want to check that a column is NOT visible/available.

**Comment by mvysny** [comment]
Ah, in such case please use `assertNull(grid.getColumnByKey(key))`.
