### ISSUE TITLE
Support for tabs

### ISSUE THREAD

**Issue by satorstefan** [mvysny/karibu-testing#155]
Hello Martin,

currently I use tabsComponent.selectTab(tab), but there should be a _click methode like for buttons dont you think?

public void selectType(ObjectType type) {
        isVisible();
        TabsComponent tabsComponent = _get(TabsComponent.class);
        Tab tab = null;
        switch (type) {
            case WorkEquipment:
                tab = _get(tabsComponent, Tab.class, spec -> spec.withId(ObjectTabs.WORK_EQUIPMENT_TAB));
                break;
            case Operation:
                tab = _get(tabsComponent, Tab.class, spec -> spec.withId(ObjectTabs.OPERATION_TAB));
                break;
            case Environment:
                tab = _get(tabsComponent, Tab.class, spec -> spec.withId(ObjectTabs.ENVIRONMENT_TAB));
                break;
        }
        tabsComponent.selectTab(tab);
    }

**Comment by mvysny** [comment]
If I understand correctly, you would like to have a `Tab._click()` function which would select that particular tab?

**Comment by satorstefan** [comment]
Yes, something like that.

I just found that vaadin v24 has a TabSheet class(Just since v23.2):
https://vaadin.com/docs/latest/components/tabs

So I would like to have something like:
TabSheet_.click("TabLabel") 
and / or 
Tab_.click("TabLabel")
with the usual checks for visibility/enabled.

**Comment by satorstefan** [comment]
Hello Martin,

will you continue adding new features to karibu or should I consider switching to the official vaadin tool/ [UI Unit Testing](https://vaadin.com/docs/latest/testing/ui-unit)?

**Comment by mvysny** [comment]
The two projects now evolve independently.

What is the use-case for `_click()` on a Tab that isn't fulfilled by TabSheet.setSelectedTab()?

**Comment by satorstefan** [comment]
One reason I use Karibu is that the visibility and enabled YES/NO checks are included when using the methods provided by Karibu.

I assume this is not the case when using TabSheet.setSelectedTab(), correct?

**Comment by mvysny** [comment]
Good point! While it is not possible to select a disabled tab (TabSheet.setSelectedTab() does nothing for a tab that's not enabled), it's possible to programatically select an invisible tab.

I'd recommend to call the function `_select()` instead, to be in line with the terminology used by TabSheet: i.e. TabSheet has selected tab, not a "tab that was clicked".

I need to test whether it's possible to get the parent `Tabs` from a `Tab`: if not, the function needs to go to `Tabs`/`TabSheet`.

**Comment by satorstefan** [comment]
`_select()` is fine for me.

**Comment by mvysny** [comment]
Implemented in Karibu-Testing 2.1.1, depend on `karibu-testing-v23` or higher to use.
