### ISSUE TITLE
How to click on a Button in a column?

### ISSUE THREAD

**Issue by simasch** [mvysny/karibu-testing#157]
I have added three buttons in a HorizontalLayout with addComponentColumn.

How can I click one of these buttons? I've only found _clickRenderer which probably would click on the component.

**Comment by mvysny** [comment]
Hi, that is correct, `_clickRenderer()` will only click on a component that implements `ClickNotifier`.

You need to get the `HorizontalLayout` via `_getCellComponent()`, then locate the button out of `HorizontalLayout` (e.g. via `_get()`), then click on the button (e.g. via `_click()`).

Please see https://github.com/mvysny/karibu-testing/tree/master/karibu-testing-v10#clicking-renderers for more details.

**Comment by simasch** [comment]
Hi @mvysny 
thanks a lot for your help. Works like a charm.
