### ISSUE TITLE
Can't use maven dependencies

### ISSUE THREAD

**Issue by sedstef** [mvysny/karibu-testing#16]
When adding maven dependencies in pom.xml, I get the error:
_Failed to collect dependencies at com.github.mvysny.kaributesting:karibu-testing-v10:jar:1.1.0: Failed to read artifact descriptor for com.github.mvysny.kaributesting:karibu-testing-v10:jar:1.1.0: Failure to find com.vaadin:vaadin-bom:pom:13.0.0.beta1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]_

My pom.xml, only using default maven repositories:
```xml
        <dependency>
            <groupId>com.github.mvysny.kaributesting</groupId>
            <artifactId>karibu-testing-v10</artifactId>
            <version>1.1.3</version>
            <scope>test</scope>
        </dependency>
```

**Comment by sedstef** [comment]
I found the problem, vaadin-prereleases repository is missing. After adding
```xml
<repositories>
        <!-- Repository needed for prerelease versions of Vaadin -->
        <repository>
            <id>vaadin-prereleases</id>
            <url>https://maven.vaadin.com/vaadin-prereleases</url>
        </repository>
    </repositories>
```
vaddin 13.0.0.0beta1 could be found.
Maybe you should change your dependencies to depend only on stable releases?

**Comment by mvysny** [comment]
Hi, thanks for trying out karibu-testing! Yeah, karibu-testing 1.1.x is
only compatible with Vaadin 13 and requires the vaadin-prereleases Maven
repo, as you correctly pointed out.
The compatibility chart is present at
https://github.com/mvysny/karibu-testing/blob/master/karibu-testing-v10/README.md
, but it should definitely benefit from increased visibility and should
mention the Maven repo. Please let me know where this information would
make most sense. Thanks!

**Comment by sedstef** [comment]
Ooh, I saw this before, I think the README is the correct place. My main problem is autowiring Spring services into the constructor of the Vaadin view, so I tried the newest karibu version, and I ran into this Problem. You can close this issue. if I can't solve the Spring autowiring problem, I'll create a new issue.

**Comment by mvysny** [comment]
Sure, no problem! Closing the issue as agreed.

Note: There is an example app using Karibu-Testing with Spring here: https://github.com/mvysny/karibu-testing-spring , perhaps it might be helpful.
