### ISSUE TITLE
expectNotification not working

### ISSUE THREAD

**Issue by avdhootu27** [mvysny/karibu-testing#165]
In my code I am showing notification as `Notification.show("Done!")` but in its test when I test it as `expectNotifications("Done!)` it says: `java.lang.AssertionError: Expected <[Done!]>, actual <[]>.`
Am i correctly testing it? If yes, why test is not passing?

**Comment by mvysny** [comment]
That's the correct usage. Could be that `expectNotifications()` is broken for some Vaadin version. Which Vaadin version are you using please?

**Comment by avdhootu27** [comment]
I am using vaadin 14.11.0, karibu-testing-v10-spring 1.3.24

**Comment by avdhootu27** [comment]
I just found that if I add `MockVaadin.clientRoundtrip()` before `expectNotifications()`, It works.

**Comment by mvysny** [comment]
Tested with Vaadin 14.11.5, works for me. Please provide a test case or a project which reproduces the issue. Are you sure you haven't reconfigured the `TestingLifecycleHook`?

**Comment by avdhootu27** [comment]
I have reconfigured the TestingLifecycleHook

**Comment by mvysny** [comment]
Yup, you have to be super-careful when reconfiguring the hook and always call `clientRoundtrip()`. I've added a kdocumentation in this spirit.
