### ISSUE TITLE
testing Dialog

### ISSUE THREAD

**Issue by avdhootu27** [mvysny/karibu-testing#166]
I am testing a method which opens a dialog by `myDialog.open()` and I am checking it as `_get(Dialog.class)`  But getting `java.lang.AssertionError: /my-view: No visible Dialog in UI[] matching Dialog

Is there any different way to test Dialog? I am using karibu-testing-v10-spring with vaadin 14.

**Comment by mvysny** [comment]
The dialog should append itself as a child to the UI upon open, therefore `_get(Dialog.class)` should be able to locate it. Can you observe this behavior?

**Comment by mvysny** [comment]
The UI itself.

**Comment by avdhootu27** [comment]
Can you please elaborate what do you mean by "Can you observe this behavior?", The dialog opens and I can see it when the app is running, but in tests it doesn't get append to UI, and I am not getting any errors

**Comment by mvysny** [comment]
Sure thing. Say you have this kind of a test:
```java
    @Test
    public void testGreeting() {
        new Dialog().open();
        MockVaadin.clientRoundtrip();
        System.out.println(PrettyPrintTreeKt.toPrettyTree(UI.getCurrent()));
    }
```
It should print the following tree:
```java
└── MockedUI[]
    ├── MainView[@class='centered-content', @style='width:100%', @theme='padding spacing']
    │   ├── TextField[label='Your name', value='', @class='bordered']
    │   └── Button[text='Say hello', @theme='primary']
    └── Dialog[]
```
Note that the Dialog component attaches itself as the direct child of the UI (represented by the MockedUI component). Also note the clientRoundtrip() function - dialog attaches itself lazily by default, and clientRoundtrip() forces eager attachment.

In your case, can you see the Dialog component in the component dump?

**Comment by avdhootu27** [comment]
Thanks. It worked. I just added `MockVaadin.clientRoundtrip()` and `_get(Dialog.class)` was able to locate it.
I didn't know about `MockVaadin.clientRoundtrip()`. I am closing this issue now.

**Comment by mvysny** [comment]
What's strange is that `_get()` should call `MockVaadin.clientRoundtrip()` automatically - you should not have to worry about it. I'll rather reopen this ticket and investigate.

**Comment by avdhootu27** [comment]
Ok.
FYI, while closing the dialog I needed to use `MockVaadin.clientRoundtrip()`

**Comment by mvysny** [comment]
I've upgraded Karibu-Testing testing suite to Vaadin 14.11.5 and ran the test suite. The test suite is really extensive and tests all sorts of scenarios, including the Dialogs. The tests seem to pass and I don't have to call `MockVaadin.clientRoundtrip()` manually. In other words, I can't reproduce the issue. I'll need the simplest possible app/test case which reproduces the issue.

Side question: Maybe you have hooked into `TestingLifecycleHook` and removed the call to clientRoundtrip()?

**Comment by avdhootu27** [comment]
Right, I have hooked into TestingLifecycleHook, I didn't know that caused it. Thanks

**Comment by mvysny** [comment]
Alrighty, no worries. I've updated the docs to stress out the importance of calling the original hook.

**Comment by avdhootu27** [comment]
Is there any case in which we get NullPointerException on `MockVaadin.clientRoundtrip()` ?
