### ISSUE TITLE
_click in SideNavUtils has incorrect NavigationTrigger type

### ISSUE THREAD

**Issue by Sam-k-Elliott** [mvysny/karibu-testing#168]
The Side Navigation Component triggers a navigation event of type `CLIENT_SIDE` when clicked however the Karibu `_click` functionality for this component generates a navigation event of type `UI_NAVIGATE`

Noticed this issue when switching out our bespoke left nav for the out-of-the-box side nav component Vaadin now provides.  We intercept Navigation events via a `BeforeLeaveObserver` and have handling that pivots off of the navigation event type. This made the vaadin functionality untestable with the current implementation of `_click` in `SideNavUtils`

We ended up just pulling out the internal functionality that `_click` uses and passing the proper navigation event type into it but it would be nice if the Karibu behavior could match the Vaadin behavior.

**Comment by mvysny** [comment]
Sounds good! I'll add the trigger parameter to _click() defaulting to CLIENT_SIDE
