### ISSUE TITLE
Vaadin 10: Add support for clicking on a Grid row

### ISSUE THREAD

**Issue by nils-christian** [mvysny/karibu-testing#17]
Hi,

This is similar to #2. We have a Vaadin grid with an item click listener: `grid.addItemClickListener(...)`

Currently there seems no API to perform this click on the whole row. Using the _clickRenderer_ method just leads to a _ClassCastException_, because the column itself is not clickable, but just the row.

Is there another possibility to perform the click?

Best regards,

  Nils

**Comment by mvysny** [comment]
Thanks! There was `Grid._clickItem()` for Vaadin 8; I forgot to add such a method for Vaadin 10+. Implemented in Karibu-Testing 1.1.4
