### ISSUE TITLE
SearchSpecJ seems to be missing theme-related matchers

### ISSUE THREAD

**Issue by TheHaf-at-FraunhoferIOSB** [mvysny/karibu-testing#172]
I saw in the [documentation](https://github.com/mvysny/karibu-testing/tree/master/karibu-testing-v10#searchspecsearchspecj) that it should be possible in SearchSpec/SearchSpecJ to define a matcher for themes/withoutThemes. The respective methods are available in SearchSpec, but apparently not in SearchSpecJ, if I understand correctly.

I could try to create a PR if you are interested.

**Comment by mvysny** [comment]
You're right, thanks for pointing it out. Please feel free to create a PR for master; I'll then cherry-pick it for 1.4.x

**Comment by TheHaf-at-FraunhoferIOSB** [comment]
Alright, I'll create a PR right away. :+1:
