### ISSUE TITLE
Error message for getFormatted shows incorrect values

### ISSUE THREAD

**Issue by nils-christian** [mvysny/karibu-testing#18]
Hi,

When using the _getFormatted_ method for the grid, the method tries to find the column by key. However, if it cannot be found, the method returns the available column ids and not the keys. So it says

`java.lang.IllegalArgumentException: There is no column <...>. Available columns: [Optional.empty, Optional.empty, Optional.empty, Optional.empty]`

even if some (or all) of the columns have a key (but no id). Also the error message should not display the empty optionals and only the content of the non-empty optionals.

Best regards,

Nils

**Comment by mvysny** [comment]
You're right, thank you for letting me know! Fixed in Karibu-Testing 1.1.4.
