### ISSUE TITLE
No user principal set

### ISSUE THREAD

**Issue by F43nd1r** [mvysny/karibu-testing#180]
Due to Vaadin querying the principal from the request behaviour is different in tests vs production:

https://github.com/vaadin/flow/blob/afd284bd8892818ca797402aea73346ae6862420/flow-server/src/main/java/com/vaadin/flow/server/auth/NavigationAccessControl.java#L257-L274

Because `FakeRequest` never provides a user principal, errors are redirected to login instead of error view.
Workaround for me as I'm using spring security:
```kotlin
MockVaadin.mockRequestFactory = {
    object : FakeRequest(it) {
        override fun getUserPrincipal() = SecurityContextHolder.getContext().authentication
    }
}
```

It'd be nice if this library would pick up the user from spring by default.

**Comment by mvysny** [comment]
Spring support is handled by the `karibu-testing-v10-spring` add-on documented at https://github.com/mvysny/karibu-testing/tree/master/karibu-testing-v10-spring . Perhaps `MockSpringServlet` could set the above-mentioned `mockRequestFactory` in its `static{}` initializer... plus we can document this in the README.md. What do you think?

**Comment by F43nd1r** [comment]
Ah, from that documentation I found #94, which this is probably a duplicate of. I think it'd be great to integrate something like this in the spring module, but I'm gonna close this as duplicate and watch #94 instead.
