### ISSUE TITLE
LocatorJ._setValue(@NotNull HasValue<?, V> self, @Nullable V value, boolean fromClient) should be public

### ISSUE THREAD

**Issue by SebastianDietrich** [mvysny/karibu-testing#181]
It's the only method in LocatorJ that is package-private and thus cannot be used in tests.
Nevertheless the documentation mentions that one should use it when isFromClient needs to be true to test a code reacting to such events.
https://github.com/mvysny/karibu-testing/tree/master/karibu-testing-v10#changing-values

**Comment by mvysny** [comment]
Must be something I accidentally omitted, sorry about that :) Will be fixed in Karibu-Testing 2.2.1
