### ISSUE TITLE
SpringBoot and Vaadin 13

### ISSUE THREAD

**Issue by swebb99uk** [mvysny/karibu-testing#19]
Hi there, I tried to make use of the project to test some Vaadin 13 with SpringBoot code that I have been working on but failed at the first hurdle.

In the demo t-shirt project for SpringBoot testing which is using Vaadin 10 it used the following code.

`final RouteRegistry registry = new
Routes().autoDiscoverViews("com.vaadin.tshirtshop").createRegistry();`

However for Vaadin 13 there does not appear to be a createRegistry method. I played around a little while trying to figure out how to wire things up but basically didn't get it working.

Any tips on what I need to do, I obviously need to setup the servlet and the context but I think Vaadin 13 has changed a bit under the hood ?

Thanks

Steve

PS: great project by the way, it is really needed.

**Comment by appreciated** [comment]
@swebb99uk maybe this helps
```
Routes routes = new Routes().autoDiscoverViews("com.vaadin.tshirtshop");
MockVaadin.setup(routes);
```

**Comment by HaydenDekker** [comment]
Firstly, Great Testing Suite!!

I ran into this problem shortly into my setup. Then what happened is Spring chose the com.vaadin.flow.di.instantiator over the com.vaadin.flow.spring.instantiator and as such my @Autowire - ing in the Layout classes didn't work. After looking into the earlier solutions I added the following to the test setup.

```
final Routes registry = new Routes().autoDiscoverViews("com.me.test");
    	RouteRegistryInitializer rri = new RouteRegistryInitializer();
    	Set<Class<?>> routes = new HashSet<Class<?>>(registry.getRoutes());
    	rri.onStartup(routes, sctx);
    	RouteRegistry rr = ApplicationRouteRegistry.getInstance(sctx);
    	
        final SpringServlet servlet = new SpringServlet(ctx, true) {
            @Override
            protected VaadinServletService createServletService(DeploymentConfiguration deploymentConfiguration) throws ServiceException {
                final VaadinServletService service = new SpringVaadinServletService(this, deploymentConfiguration, ctx) {
                    @Override
                    protected boolean isAtmosphereAvailable() {
                        return false;
                    }

                    @Override
                    protected RouteRegistry getRouteRegistry() {
                        return rr;
                    }

                    @Override
                    public String getMainDivId(VaadinSession session, VaadinRequest request) {
                        return "ROOT-1";
                    }
                };
                service.init();
                return service;
            }
        };
        MockVaadin.setup(MockedUI::new, servlet);

```
Worked like a charm afterwards. Not sure what I'll run into next.

**Comment by mvysny** [comment]
Thank you guys for great solution, and I apologise that I haven't posted to this thread. To be honest I don't use spring myself and therefore I wouldn't be of much help anyway :)

Anyway, thank you @HaydenDekker for solving this issue. Closing as fixed, please reopen if there are issues.
