### ISSUE TITLE
GridContextMenu with submenu

### ISSUE THREAD

**Issue by jcgueriaud** [mvysny/karibu-testing#21]
Hello,

When I try to test a click on a submenu of the GridContextMenu and I've got this error:

`java.lang.AssertionError: Unexpected parent GridMenuItem[text='Affaires']`
`	at kotlin.test.DefaultAsserter.fail(DefaultAsserter.kt:16)`
	`at kotlin.test.AssertionsKt__AssertionsKt.fail(Assertions.kt:91)`
	`at kotlin.test.AssertionsKt.fail(Unknown Source)`
	`at com.github.mvysny.kaributesting.v10.ContextMenuKt.checkMenuItemVisible(ContextMenu.kt:97)`
	`at com.github.mvysny.kaributesting.v10.ContextMenuKt._click(ContextMenu.kt:71)`

I think hierarchical GridMenuItem is a new feature of vaadin 13 and in ContextMenu.kt the function checkMenuItemVisible does not check if parent is a GridMenuItem (I tried to read Kotlin code but I'm not sure if I understand correctly :))

Thanks,

**Comment by mvysny** [comment]
Good catch, thank you! It seems that I forgot to test this case of clicking a submenu of a Grid.

**Comment by jcgueriaud** [comment]
That's a fast feedback :).

Thank you (for the feedback and this nice project ;) )

**Comment by mvysny** [comment]
Thanks ;) Should be fixed now. Please let me know if there is anything else to fix; if not, I'll release a new version today :)

**Comment by jcgueriaud** [comment]
I don't see anything else for today. thanks
