### ISSUE TITLE
JvmOverloads on GridKt._clickItem

### ISSUE THREAD

**Issue by tborkowski** [mvysny/karibu-testing#22]
Hi there :)

Could you add overloaded methods for GridKt._clickItem method with default values?
Getting a column in Java every time when I need to click a row item looks quite redundant.

Best regards

**Comment by tborkowski** [comment]
Thanks a lot :)

**Comment by mvysny** [comment]
No problem :) Released as 1.1.6, please try it out

**Comment by tborkowski** [comment]
Great! :) It works fine.
Thanks for fast release.

czw., 9 maj 2019 o 12:52 Martin Vysny <notifications@github.com> napisał(a):
