### ISSUE TITLE
Add a cookie to the initial request

### ISSUE THREAD

**Issue by Illidanek** [mvysny/karibu-testing#23]
Note: I am using **Java8**.

I am testing my UI, which at the start reads the user's cookies. I want to be able to inject various cookies into the initial MockRequest.

The Readme says to use `currentRequest.mock.addCookie(Cookie("foo", "bar"))` however I cannot find this "currentRequest" variable anywhere, nor do I know how to insert the cookie before the UI is started.

My Test class looks something like this:

     
    @RunWith(SpringRunner.class)
    @SpringBootTest
    @WebAppConfiguration
    @DirtiesContext
     public class MyTest {

    @Autowired
    private BeanFactory beanFactory;

    @Before
    public void setup() {
        UIScopeImpl.setBeanStoreRetrievalStrategy(new SingletonBeanStoreRetrievalStrategy());
        MockVaadin.setup(() -> beanFactory.getBean(MyUI.class));
    }

    @Test
    public void notLoggedInUserGetsTheLoginPage() {
        assert(UI.getCurrent().getContent().equals(beanFactory.getBean(LoginPage.class)));
    }

    @Test
    public void loggedInUserGetsTheMainPage() {
        // For this test to work I need to insert a cookie into the MockRequest that goes into MyUI.class
        assertFalse(UI.getCurrent().getContent().equals(beanFactory.getBean(LoginPage.class)));
    }

    @After
    public void tearDown() {
        MockVaadin.tearDown();
    }
}

The first test works, because the default request has no cookies and my code displays the login page in that case.

How can I inject cookies into the MockRequest?

**Comment by mvysny** [comment]
Hi, I'm sorry, I only listed examples in Kotlin and I omitted examples in Java. I've updated the page at https://github.com/mvysny/karibu-testing/tree/master/karibu-testing-v8 with Java examples, could you please take a look whether the examples work for you?

**Comment by Illidanek** [comment]
Thanks! I have been able to add the cookie, but now I need the first VaadinRequest that comes into MyUI to have that cookie.
Or maybe otherwise, how do I initiate a mock call to my UI after I set the cookie?

**Comment by mvysny** [comment]
Right... The mocked request is created in `MockVaadin.setup()`; `VaadinRequest.getCurrent()` will return null before `MockVaadin.setup()` is called so that's not an option.

The only way I can see is to set the cookie in the UI creation closure passed into `MockVaadin.setup()`, something like this:

```java
MockVaadin.setup(() -> {
  MockVaadinKt.getMock(VaadinRequest.getCurrent()).addCookie(new Cookie("foo", "bar"));
  return beanFactory.getBean(MyUI.class));
});
```
Let me test this, and if it works, I'll document this possibility.

**Comment by mvysny** [comment]
Yup, it works, I've updated the documentation at https://github.com/mvysny/karibu-testing/tree/master/karibu-testing-v8 - could you please check it out whether the documentation is clear?

**Comment by Illidanek** [comment]
Brilliant! That works.
You are a saviour.

**Comment by mvysny** [comment]
No problem, have a nice day :wave:
