### ISSUE TITLE
Readme uses an import from another tool

### ISSUE THREAD

**Issue by Illidanek** [mvysny/karibu-testing#24]
In the readme, there is a piece of example code:

    import static com.github.mvysny.kaributesting.v8.LocatorJ.*;
    import static com.github.vok.karibudsl.NavigatorKt.*;
    public class MyUITest {
    @BeforeAll
    public static void beforeAll() {
        autoDiscoverViews("com.myproject")
    }

    @BeforeEach
    public void beforeEach() {
        MockVaadin.setup(MyUI::new);
    }

    @Test
    public void simpleTest() {
        navigateToView(CrudView.class);  // this will call Navigator.navigateTo("crud")

        // now the view is ready and attached to your UI. We can test.
        final Grid<Person> grid = _get(Grid.class);
        // etc etc
    }
    }

note the line: `import static com.github.vok.karibudsl.NavigatorKt.*;`

This is an import that does not work for me and is not included in the maven dependency of this library. Is this incorrect or am I doing something wrong?

**Comment by mvysny** [comment]
I see. The `NavigatorKt` comes from the [Karibu-DSL](https://github.com/mvysny/karibu-dsl) library, however you're right in a way that Karibu-Testing doesn't depend on (and should not depend on) Karibu-DSL in any way. Let me change the example please.
