### ISSUE TITLE
autoDiscoverViews cannot be found

### ISSUE THREAD

**Issue by Illidanek** [mvysny/karibu-testing#25]
I am trying to run `autoDiscoverViews("X.Y.Z")` before my tests, but it does not even compile, and my IDE cannot find this method anywhere.
I am following the README, without success.

Am I doing something wrong?

**Comment by mvysny** [comment]
Thanks for pointing that out! The `autoDiscoverViews()` function is provided by Karibu-DSL and only works when you're using the `@AutoView` and `AutoViewProvider`. I've modified the documentation to explicitly state this fact.

If you're not using Karibu-DSL, please only take the first chapter of the "Navigation" section into consideration.
