### ISSUE TITLE
Testing of GridPro component

### ISSUE THREAD

**Issue by nbabb** [mvysny/karibu-testing#28]
Hi Martin,

We are evaluating GridPro and one of the things we're looking at is testing.  GridPro allows cell editing through a double-click.  I see in Grid.kt code for clicking a cell Renderer (i.e. _clickRenderer).  I started to model an approach after what you have there.  

By default the GridPro column renderer is ColumnPathRenderer (which doesn't supply a Component).  I was thinking that once I get the component I could fire two click events.  I'd prefer a solution where I don't have to change the default renderer of GridPro.  

Will I need to use a ComponentRenderer and call createComponent and fire click events for this component in order to enter into edit mode for a cell?  Suggestions appreciated.

Thanks

**Comment by mvysny** [comment]
Hi, hmm, it could be that GridPro listens for some double-click event which even bypasses the renderers altogether. Please let me take a look at the GridPro sources - perhaps there is an easier way to show the editor from the server-side.

If I understand correctly, the task is just to open an editor for a particular row, is that correct? Then we should be able to target individual editor components and click the "Save" button from server-side.

**Comment by nbabb** [comment]
Yes.  The desired behavior would be to double-click to edit.  Then change a value and close the editor (loss of focus) and commit the value to the component's model.  Thanks for checking!

**Comment by nbabb** [comment]
I was able to get something working here 
```        GridPro grid = (GridPro) gridWrapper.grid()
        BeanItem item = _get(gridWrapper.grid(), 0)
        item.setStringField("some changed value")

        JreJsonObject jsonObject = new JreJsonObject();
        jsonObject.set("key", new JreJsonString("1"))
        ComponentUtil.fireEvent(grid, new GridPro.CellEditStartedEvent<BeanItem>(grid, false, jsonObject, "col2"))
        gridWrapper.getListedItems().collect { it.stringField } == ["some changed value"]
``` with some hardcoded key/path values.

**Comment by nbabb** [comment]
So this approach works, but not ideal.

```
        GridPro grid = (GridPro) gridWrapper.root
        JreJsonObject jsonObject = new JreJsonObject();
        jsonObject.set("key", new JreJsonString("1"))
        jsonObject.set("col2", new JreJsonString("some changed value"))

//        ComponentUtil.fireEvent(grid, new GridPro.CellEditStartedEvent<BeanItem>(grid, false, jsonObject, "col2"))
        ComponentUtil.fireEvent(grid, new GridPro.ItemPropertyChangedEvent<BeanItem>(grid, false, jsonObject, "col2"))
        gridWrapper.getListedItems().collect { it.stringField } == ["some changed value"]
```

**Comment by mvysny** [comment]
Thank you. Initial work has been done in 74f06dbdaa7c08198140f73aa4814a2a78215270 but we need to also support invoking of the ItemUpdaters for individual columns, to also test those. Right now I'm thinking about simply adding extension property to Grid.Column such as `column._gridPro._checkbox(true)` or something along those lines, but please feel free to suggest alternative API.

**Comment by mvysny** [comment]
The support for mocking inline Grid Pro editor has been added; please see the readme on how to use it: https://github.com/mvysny/karibu-testing/tree/master/karibu-testing-v10

Just let me know if there is something more needed for a proper GridPro testing.
