### ISSUE TITLE
Add support for @Autowired constructor parameters for vaadin 10

### ISSUE THREAD

**Issue by ilya-ershov** [mvysny/karibu-testing#3]
Currently, karibu testing requires to have no args constructor. But we are using Spring and DI into constructor so karibu fails to instantiate a View component. Is there a way to make karibu-testing use current @SpringBootTest context for autowired fields? Or is there a workaround to inject spring dependencies into mocked ui?

**Comment by ilya-ershov** [comment]
I'm still developing a cleaner solution for my app with the use of Java SPI, but what works now is that piece of code that I inserted in your sources at line MockVaadin:56:

`                    override fun loadInstantiators(): Optional<Instantiator> {
                        val spiInstantiator = super.loadInstantiators()
                        val springInstantiators = context
                                .getBeansOfType(Instantiator::class.java).values.stream()
                                .filter({ instantiator -> instantiator.init(this) })
                                .collect(Collectors.toList<Instantiator>())
                        if (spiInstantiator.isPresent && !springInstantiators.isEmpty()) {
                            throw ServiceException(
                                    "Cannot init VaadinService because there are multiple eligible "
                                            + "instantiator implementations: Java SPI registered instantiator "
                                            + spiInstantiator.get()
                                            + " and Spring instantiator beans: "
                                            + springInstantiators)
                        }
                        if (!spiInstantiator.isPresent && springInstantiators.isEmpty()) {
                            val defaultInstantiator = SpringInstantiator(this,
                                    context)
                            defaultInstantiator.init(this)
                            return Optional.of(defaultInstantiator)
                        }
                        return if (spiInstantiator.isPresent)
                            spiInstantiator
                        else
                            springInstantiators.stream().findFirst()
                    }
`
The original method defined in VaadinService uses simple `ServiceLoader.load(Instantiator.class, getClassLoader())` to locate the class via JavaaSPI. So no hack of sources needed, just need to learn how to use java spi to inject the service.

**Comment by ilya-ershov** [comment]
Ok update here. It's very hard to establish Spring support through JavaSPI, because I couldn't find a clear way to inject Spring context into located service. ReflectionUtils helps but thats barely a solution.
Would be a great help, if you expose some way to add custom Instantiators to VaadinServlet object.
SpringInstantiator depends on VaadinService and ApplicationContext as constructor parameters.

**Comment by mvysny** [comment]
Something like this:
```
    fun setup(routes: Routes = Routes(), uiFactory: ()->UI = { MockedUI() },
              serviceFactory: (VaadinServlet, DeploymentConfiguration, Routes) -> VaadinServletService = { servlet, dc, routes -> MockService(servlet, dc, routes) }) {
        // init servlet
        val servlet = object : VaadinServlet() {
            override fun createServletService(deploymentConfiguration: DeploymentConfiguration): VaadinServletService {
                val service = serviceFactory(this, deploymentConfiguration, routes)
                service.init()
                return service
            }
        }
        val ctx = MockContext()
        servlet.init(MockServletConfig(ctx))
        VaadinService.setCurrent(servlet.service!!)

        // init Vaadin Session
        createSession(ctx, servlet, uiFactory)
    }
```
The MockService class:
```
class MockService(servlet: VaadinServlet, deploymentConfiguration: DeploymentConfiguration, routes: Routes) : VaadinServletService(servlet, deploymentConfiguration) {
    private val registry = routes.createRegistry()
    override fun isAtmosphereAvailable(): Boolean = false
    override fun getRouteRegistry(): RouteRegistry = registry
    override fun getMainDivId(session: VaadinSession?, request: VaadinRequest?): String = "ROOT-1"
}
```

**Comment by mvysny** [comment]
Please try out the newest solution if it works for you - if yes, I'll release a new version of the library.

**Comment by ilya-ershov** [comment]
Thank you for quick update. But now its interop with Java is completely broken. 
1. Now without dependencies on Kotlin stdlib following code doesnt compile (complains, that Function0 and Function3 are not a functional interfaces):
`MockVaadin.INSTANCE.setup(routes,MockedUI::new,MockService::new)`
2. MockService is final and can't be extended to override instantiators method

And all that kotlin object stuff makes it unintuitive to use from Java or Groovy. 
I'll try to express myself in a snippet of code later today.

**Comment by mvysny** [comment]
Thanks, good to hear that we're moving to the right direction. Couple of remarks:

1. The API of the library was built using Kotlin language in mind; I believe the API may be hard to use from Java. But, you can still instantiate Function3 as anonymous inner class.
2. I thought the MockService to be just a blueprint - just copy the class to your code and alter it as you see fit :)

**Comment by ilya-ershov** [comment]
1. Happily kotlin provides ways to optimize it to look more concise. I'd like to use kotlin, but everything that I have right now is Groovy and Java 10. Yes, I can, but I need to define kotlin dependencies to use Function3. 
2. Yes, but you do some setup in MockService that Im not really familar with why it should be in such way. So wanted to just extend your solution, because it's already working :)

**Comment by ilya-ershov** [comment]
You are right, I've spotted later on that there are lots of places where SAM can be used, so no point to use it only in one place. kotlin Function will work ok.
Cool, I'll update the patch soon

**Comment by mvysny** [comment]
Hmm, I just tried the following Java code which works, even though `Function0` nor `Function` is annotated with `@FunctionalInterface` - probably it's automatically SAM or something like that :)

**Comment by ilya-ershov** [comment]
Function0 worked, but Function3 was not working for me :)

**Comment by mvysny** [comment]
Interesting, `Function3` is working for me as well from Java 8. Pushed: please check out the `JavaAPITest` class

**Comment by ilya-ershov** [comment]
Tried. Hm, the same result as for you. Not sure how I was able to get that my previous result. Function0-3 works fine. The only concern is that its damn hard readable. But that goes to all kotling parametrized stuff so not an issue.
