### ISSUE TITLE
Support for Spring Boot 2.3.1

### ISSUE THREAD

**Issue by chrisw73** [mvysny/karibu-testing#41]
Hi Martin!

In our Vaadin 14 project we use this parent in our maven pom.xml

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.2.0.RELEASE</version>
    </parent>

As soon as we update to 2.3.1 Karibu fails completely.
One issue ist, that _get produces InternalServerError s.

Are we doing something wrong or just braks Sping Boot the compatibility?

Regards,
Christoph

**Comment by mvysny** [comment]
Hi, thanks for reaching out! I'm not sure what exactly causes the problematic behavior in your case, but please take a look at https://github.com/mvysny/t-shirt-shop-example - it uses spring boot 2.3.0 and it should work properly.

**Comment by mvysny** [comment]
Hi @chrisw73  were you able to resolve the issues you were having please?

**Comment by christoph73** [comment]
The only problem we have with Karibu is that there is no problem 😄. The issue can be closed eventually. 👍🏻

**Comment by mvysny** [comment]
Haha, that's excellent to hear :-D I'm happy that all issues have been resolved :+1: 

Closing the issue as agreed.
