### ISSUE TITLE
[bug] [UI|Session][Init|Destroy]Listener not called

### ISSUE THREAD

**Issue by thigg** [mvysny/karibu-testing#43]
Version 1.1.27

The SessionInitListeners are not called when a new session is created.

#42 should fix this

Also [ ] SessionDestroyListener, UIInitListener and UIDestroyListener should be invoked.

 - [x] SessionInitListener
 - [ ] SessionDestroyListener
 - [ ] UIInitListener
 - [ ] UIDestroyListener

**Comment by mvysny** [comment]
Excellent, thank you for letting me know.

I'll also add tests for this.

**Comment by mvysny** [comment]
In fact, none of the uiInitListeners nor sessionDestroyListeners are invoked. I'll add tests for that too.

**Comment by mvysny** [comment]
I have actually revisited the `MockVaadin.tearDown()` and noticed that the session/ui/service was not closed properly. Karibu-Testing will now try to close all of those objects properly like Vaadin would, but that could bring incompatibilities.

Could you please try to build the newest Karibu-Testing 1.1.x from sources and try it out with your project, to see whether there are any issues?

**Comment by thigg** [comment]
yes, works for me. thanks!

**Comment by thigg** [comment]
Do we see a release soon?

**Comment by mvysny** [comment]
Not sure... but since this functionality could potentially be breaking, maybe we should release and gather feedback on the feature.

**Comment by thigg** [comment]
actually found something:
I used
```
 new VaadinServletService{
...
}
```
at some point, had to replace this with MockService now... this is rather unfortunate...

**Comment by mvysny** [comment]
Actually I've dropped the custom listeners from MockService and I'm looking up listeners from VaadinService's private fields :) So you can revert the code back to VaadinServletService

**Comment by thigg** [comment]
Then we need to fix https://github.com/mvysny/karibu-testing/blob/master/karibu-testing-v10/src/main/kotlin/com/github/mvysny/kaributesting/v10/MockVaadin.kt#L261 as well ;)

**Comment by mvysny** [comment]
Oh damn :-D

**Comment by mvysny** [comment]
Fixed in 7c28d4f517617e11786418960cfb650f7e2b5e11

**Comment by mvysny** [comment]
Okay, I've released 1.1.29; it will take a bit of time until in appears in Maven Central though.
