### ISSUE TITLE
Use of GridKt.expectRow with a custom renderer

### ISSUE THREAD

**Issue by nbabb** [mvysny/karibu-testing#44]
We have a ComponentRenderer that creates a Div and then Spans within for multi-line presentation.  There are cases where testing the actual renderer output is desirable, due to manipulations which may occur there.

Previously with the default ColumnPathRenderer we were able to extract the actual value.  Now with our custom renderer the output comes out as "Div[]" which isn't very helpful for testing.

Do you have any suggestions for us (other than implementing a custom solution where we might enhance Grid.kt getPresentationValue method to deal with our custom renderer)?  

A simple solution could be for the ComponentRenderer block of getPresentationValue to be enhanced to do a deeper representation than component.toPrettyString() does currently.  Though I suppose that would break backward compatibility.

Or perhaps there could be some sort of abstraction, registered with the renderer type, for navigating the expected renderer component tree and return a value.

Thanks

**Comment by mvysny** [comment]
Hi, I think I may have exactly what you need; I just forgot to document it :-D

It's now documented, please see https://github.com/mvysny/karibu-testing/tree/master/karibu-testing-v10#customizing-dump-for-your-components for more details. Please let me know whether that solves your issue.

**Comment by nbabb** [comment]
That worked great!

**Comment by mvysny** [comment]
Excellent, I'm happy to hear that :) Closing as fixed.
