### ISSUE TITLE
14.4.5 grid broken - GridSorterComponentRenderer not found

### ISSUE THREAD

**Issue by thigg** [mvysny/karibu-testing#58]
Since 14.4.5 I get:

```
Caused by: java.lang.ClassNotFoundException: com.vaadin.flow.component.grid.GridSorterComponentRenderer
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.github.mvysny.kaributesting.v10.GridKt.<clinit>(Grid.kt:464)
```

This is caused by this MR: https://github.com/vaadin/vaadin-flow-components/pull/535

**Comment by mvysny** [comment]
Thanks! Yes, it has been fixed in git commit 132a6d48016428b4af415c5251208fb9709d8829 and should be present in Karibu-Testing 1.2.7 or higher. Please try it out and let me know :+1:

**Comment by thigg** [comment]
According to https://github.com/mvysny/karibu-testing/tree/master/karibu-testing-v10 14.4.5 is not compatibel to 1.2.x?

**Comment by mvysny** [comment]
It is, as long as you're not using the compatibility (bower) mode.

**Comment by thigg** [comment]
Ah thanks, didn't see that.

Is there a migration guide from 1.1 to 1.2?
I rewrote some imports and added exclusions to some dependencies, now it seems to work, but I get:
`com.vaadin.flow.router.NotFoundException: No route found for given navigation target!`

**Comment by mvysny** [comment]
I don't think there's a migration guide yet, I was hoping that all issues would be straightforward to fix :+1: 

Regarding the `NotFoundException`: please see FAQ https://github.com/mvysny/karibu-testing#faq . Are you using `autoDiscoverViews()`?

**Comment by thigg** [comment]
Yes, we're specifying 2 packages. I assume this is working, as it was working before I bumped the karibu version

**Comment by thigg** [comment]
I'm currently checking if its showing the same behavior on jenkins, if it does, I'm coming back with more info

**Comment by mvysny** [comment]
Sure, but please open a new bug report for this. Also you can check whether the route in question is present in the `Routes.routes set`.
