### ISSUE TITLE
Karibu Update...

### ISSUE THREAD

**Issue by chrisw73** [mvysny/karibu-testing#65]
Hi Martin!

We've just updated to 1.2.10 an run intu issues with the MockSpringServlet.

@Override
    public void init(ServletConfig servletConfig) throws ServletException {
        routes.register(servletConfig.getServletContext());
        super.init(servletConfig);
    }

Does niot work anymore, vor register expects a VaadinContext now. I cannot find an updated Java example anywhere. Can you pease give directions :-)...

Thanks in advance!

Christoph

P.S.: Still great Karibu fans. When will it become official part of Vaadin (asked sales person for it a couple of times ;-) )

**Comment by mvysny** [comment]
> P.S.: Still great Karibu fans. When will it become official part of Vaadin (asked sales person for it a couple of times ;-) )

Haha, awesome, thank you! I don't think Karibu-Testing will become official part of Vaadin anytime soon since currently the focus is on getting support for proper client-side tests. Also, I think as a separate offering, Karibu-Testing can move at a much faster pace ;)

**Comment by mvysny** [comment]
Hello, if the exception which you're getting is this one: 

```
Caused by: java.lang.NullPointerException
	at com.vaadin.flow.server.frontend.FrontendUtils.getStatsFromWebpack(FrontendUtils.java:402)
	at com.vaadin.flow.server.frontend.FrontendUtils.getStatsContent(FrontendUtils.java:367)
	at com.vaadin.flow.component.polymertemplate.NpmTemplateParser.getSourcesFromStats(NpmTemplateParser.java:172)
	at com.vaadin.flow.component.polymertemplate.NpmTemplateParser.getTemplateContent(NpmTemplateParser.java:105)
	at com.vaadin.flow.component.polymertemplate.TemplateDataAnalyzer.parseTemplate(TemplateDataAnalyzer.java:200)
	at com.vaadin.flow.component.polymertemplate.TemplateInitializer.<init>(TemplateInitializer.java:91)
	at com.vaadin.flow.component.polymertemplate.PolymerTemplate.<init>(PolymerTemplate.java:88)
	at com.vaadin.flow.component.polymertemplate.PolymerTemplate.<init>(PolymerTemplate.java:103)
	at org.test.MyComponent.<init>(MyComponent.java:32)
```

then that means that you're using `PolymerTemplate` and for some reason the `MockInstantiator` was not registered properly to Vaadin, which means that Vaadin is not using `MockNpmTemplateParser` to load the templates but it's using the default mechanism.

> VaadinService.getCurrent().getInstantiator() should return MockInstantiator, but It does return SpringInitiator, so mocking did NOT work

Excellent catch, that is indeed the source of the problem.

The problem looks like the `MockSpringServletService` class doesn't properly create the `MockInstantiator` as opposed to `MockService`. The `MockSpringServletService` class needs to be patched like this:

```
public class MockSpringServletService extends SpringVaadinServletService {
    @NotNull
    private final Function0<UI> uiFactory;

    public MockSpringServletService(@NotNull MockSpringServlet servlet,
                                    @NotNull DeploymentConfiguration deploymentConfiguration,
                                    @NotNull ApplicationContext ctx,
                                    @NotNull Function0<UI> uiFactory) {
        super(servlet, deploymentConfiguration, ctx);
        this.uiFactory = uiFactory;
    }

    @Override
    protected boolean isAtmosphereAvailable() {
        return false;
    }

    @Override
    public String getMainDivId(VaadinSession session, VaadinRequest request) {
        return "ROOT-1";
    }

    @Override
    protected VaadinSession createVaadinSession(VaadinRequest request) {
        return new MockSpringVaadinSession(this, uiFactory);
    }

    @Override
    public Instantiator getInstantiator() {
        return MockInstantiator.Companion.create(super.getInstantiator());
    }
}
```

Let me add tests for this please.
