### ISSUE TITLE
Rework the _clickRenderer API

### ISSUE THREAD

**Issue by mvysny** [mvysny/karibu-testing#67]
In Vaadin 14.4.8+, the Checkbox became a `ClickNotifier` which actually broke the example for the `_clickRenderer()` function.

The README lists the following example:

```
grid._clickRenderer(0, "foo", { (it as Checkbox).value = true })
```

Since Checkbox is now a `ClickNotifier`, the closure is not being called anymore, leaving the customer wondering why the ValueChangeListener is not called (and instead a ClickListener is called!).

We need to redesign the API to prevent this kind of silent functionality breakage.

**Comment by mvysny** [comment]
I will drop the `click` closure from `_clickRenderer()`. It is a breaking change, but it's better than having tests to break mysteriously after Vaadin upgrade. I will implement a `_getCellComponent()` function which will allow you to express your intent in a better way.

**Comment by chrisw73** [comment]
To complete the example:
```
myGrid.addComponentColumn(mySelectable -> {
    Checkbox checkbox = new Checkbox();
    checkbox.setValue(mySelectable.isSelected());
    checkbox.addValueChangeListener(l -> {
        mySelectable.setSelected(l.getValue());  // THIS IS NOT CALLED ANYMORE (on GridKt._clickRenderer….)
    });
    checkbox.addClickListener(l2 -> {
        System.out.println("HA“);  // JUST THIS IS (!) CALLED NOW - I do not want to place the selection code here ;-)
    });

    return checkbox;
}).setSortable(false).setKey("sel").setHeader(selectAllCheckBox);
```

Karibu Code:
`
GridKt._clickRenderer(myView.myGrid, 0, "sel");
List<MyObject> myList = myView.dataProvider.getTreeData().getRootItems().stream.filter(Selectable::isSelected).map(Selectable:get).collet(Collectors.toList());
assertEquals(1, myList()); // should be 1 but is 0
`

**Comment by mvysny** [comment]
The new way would be to use

```java
((Checkbox) GridKt._getCellComponent(grid, 0, "foo")).setValue(true);
```

The new API explicitly retrieves the component, casts it to Checkbox and calls setValue() which will fire the ValueChangeListener.

**Comment by chrisw73** [comment]
VERY (!) nice!

I am just a litte scared of „would be“, because you have pointed out, that you are pretty busy at the moment… When can I expect the „would be“-api to be released (knowin you are VERY fast usually…).

Greetinx!

**Comment by mvysny** [comment]
Perhaps today hopefully :+1:

**Comment by chrisw73** [comment]
You are the best (as always) :-)

**Comment by chrisw73** [comment]
Wow you ARE fast! And I'd like to thank you by testing ultra fast :-).
The new API is great (!).
Unfortunately I have to tell you, that just the click event of the CheckBox is being fired, not the ValueChangeEvent :-(. So my issue is not really solved, sorry...

Let me tell you, if I can provide anny assistence...

**Comment by mvysny** [comment]
You need to call both `_setValue()` to fire the ValueChangeEvent and `_click()`/`_clickRenderer()` to fire the ClickEvent

**Comment by chrisw73** [comment]
You are right... I had a test with old API... My Bad. Wors perfect! Thanks a lot!
