### ISSUE TITLE
grid._get(rowIndex) fails on Grid with undefined size

### ISSUE THREAD

**Issue by eiswind** [mvysny/karibu-testing#72]
Im struggling with testing my Grid, which loads its data like (with undefined size)

```
grid.setItems { query ->
    userPreviewRepository.findAll(query.toPageQuery())
}
```
grid._get calls _size() internally which fails with an grid of undefined size. Do you have an idea how I could workaround this behaviour?

**Comment by mvysny** [comment]
Yeah, I'll need to add support for this.

**Comment by mvysny** [comment]
Support will be added in Karibu-Testing 1.3.1

**Comment by eiswind** [comment]
Sounds great! Thx.
