### ISSUE TITLE
Add Spring example for Vaadin 10

### ISSUE THREAD

**Issue by mvysny** [mvysny/karibu-testing#8]
Add Spring example for Vaadin 10. Perhaps take an existing Spring+Vaadin 10 project and test it with Karibu Testing. Please, any suggestions on a simple Vaadin 10+Spring project?

**Comment by elmot** [comment]
https://github.com/vaadin/t-shirt-shop-example
?

**Comment by mvysny** [comment]
Done: https://github.com/mvysny/t-shirt-shop-example
