### ISSUE TITLE
Supporting EnhancedDialog

### ISSUE THREAD

**Issue by hfazai** [mvysny/karibu-testing#85]
@mvysny what do you think about supporting EnhancedDialog: https://github.com/vaadin-component-factory/enhanced-dialog

I suggest the following steps:
- Adding the EnhancedDialog dependency
- In `TestingLifecycleHook.getAllChildren()` discover components in `headerContainer`, `footerContainer` and `dialogContent`

If you are Ok, I will create a PR for this.

**Comment by mvysny** [comment]
Hi, the EnhancedDialog looks like a really useful enhancement for Vaadin. However, I'm hesitant to add the dependency to Karibu-Testing itself:
* It's a third-party library, not a core vaadin component (nor a Vaadin Pro component)
* The API of the library may change in a breaking way, and then we'll need to fix it and release new Karibu-Testing
* Where will this end? (in a sense that shall we add all component factory components?)

However, I can see that the EnhancedDialog uses `getElement().appendVirtualChild(headerContainer);`. Counter-proposal: let's prototype a way for Karibu-Testing to also include virtual child components in the list of child components. Let's see where that would lead and whether there would be a breakage or not:
* if no breakage then we can enable this by default (and perhaps add a switch somewhere to disable this functionality)
* In case of a huge breakage somewhere, we can whitelist a list of components (String class names) for which the virtual child components will be considered; the list could be present in `TestingLifecycleHook` and could include the `EnhancedDialog` class name.
What do you think @hfazai  ?

**Comment by mvysny** [comment]
Added support for retrieving virtual children out of an element: https://github.com/mvysny/karibu-testing/commit/63e979d76f7349b5c1b91fcab6c268bb471eb456

**Comment by hfazai** [comment]
Hi @mvysny, 

This looks reasonable to me. We can let customer add EnhancedDialog (or any other non-vaadin-official component) dependency and provide a way to discover virtual children.

I see that you already added a way to get virtual children from an element.  We still need to get that list when discovering components. What kind of breakage could it lead to?

**Comment by mvysny** [comment]
Just guessing here, and thinking out loud: after we modify the `TestingLifecycleHook.getAllChildren()` function to also include virtual children, certain components may suddenly have new children - e.g. Grid, Menu, or similar. I wonder: perhaps these new children could clutter the tree dump (if there will be too many)? The only way is to try it out and find out :-)

Let me try it out quickly.

**Comment by hfazai** [comment]
ah I see :)

Ok, please let me know If I can help in implementing the feature.

**Comment by mvysny** [comment]
Sure! Interestingly no tests were broken... hmmmmm weird, but also quite encouraging :-D Alright. I've pushed newest code into master. Could you please try the new code out on the EnhancedDialog whether it would now list the `headerContainer` component?

You'll need to patch the `TestingLifecycleHook.getAllChildren()` as follows:

```
...
        is MenuItemBase<*, *, *> -> {
            // also include component.children: https://github.com/mvysny/karibu-testing/issues/76
            (component.children.toList() + component.subMenu.items).distinct()
        }
        is PolymerTemplate<*> -> {
            // don't include virtual children since those will include nested components.
            // however, those components are only they are only "shallow shells" of components constructed
            // server-side - almost none of their properties are transferred to the server-side.
            // Listing those components with null captions and other properties would only be confusing.
            // Therefore, let's leave the virtual children out for now.
            // See https://github.com/mvysny/karibu-testing/tree/master/karibu-testing-v10#polymer-templates--lit-templates
            component.children.toList()
        }
        else -> component.children.toList() + component._getVirtualChildren()
...
```

**Comment by hfazai** [comment]
````KOTLIN
public fun Component._getVirtualChildren(): List<Component> =
    element.getVirtualChildren().mapNotNull { it.component.orElse(null) }
````

Actually `headerContainer` and `footerContainer` are not associated to a `Component` so that they are filtred by `mapNotNull`.

**Comment by hfazai** [comment]
Maybe we can have `val Element.componentsRecursively: List<Component>` that searches for element's children in this case

**Comment by mvysny** [comment]
Good idea! Perhaps we can use `ComponentUtil.findComponents()` to perform the search and only return components that are closest to the element being examined. Could you please try it out?

**Comment by hfazai** [comment]
Ok I'm going to create a PR for that :+1:
