### ISSUE TITLE
Is it possible to set value from client?

### ISSUE THREAD

**Issue by hfazai** [mvysny/karibu-testing#87]
Hi,

`field._value = ".."` sets the value of a field and then fires a value change event where "event.isFromClient = false".

Is it possible to simulate a value change from client?

**Comment by mvysny** [comment]
It is: https://github.com/mvysny/karibu-testing/tree/master/karibu-testing-v10#changing-values

Simply use the `textField._fireValueChange()` function.

**Comment by hfazai** [comment]
Hi Martin,

the `textField._fireValueChange()` actually works fine. But I should call it just after `textField.value = "value"`, right? 
In this case the listener is called twice as `_value` also fires the value change event. This can lead sometimes to wrong behaviour.

**Comment by mvysny** [comment]
Closing as won't fix since we failed to come up with a better solution, but please feel free to reopen&post a better solution if you find one :+1:
