### ISSUE TITLE
Vaadin 12 _getFormattedRow fails

### ISSUE THREAD

**Issue by eiswind** [mvysny/karibu-testing#9]
HI, I see the following error with Vaadin 12 beta2

java.lang.NoSuchMethodException: com.vaadin.flow.component.grid.Grid.getDataGenerator()

	at java.base/java.lang.Class.getDeclaredMethod(Class.java:2476)
	at com.github.mvysny.kaributesting.v10.GridKt.getDataGenerator2(Grid.kt:101)

Let me know if I can be of any assistance.

**Comment by mvysny** [comment]
Hi, thanks for letting me know! Apparently Grid.Column changed API between Vaadin 11 and Vaadin 12 (In Vaadin 12 we can retrieve Renderer from Column, yay!). This fix is not yet released though. I need to make sure that the karibu-testing tests run both on Vaadin 11 and Vaadin 12, to make sure both APIs are tested.

**Comment by mvysny** [comment]
I've fixed `_getFormattedRow()` so that it works both for Vaadin 11 and Vaadin 12. The Karibu-Testing internal test suite is now run both for Vaadin 11 and Vaadin 12 so that we can detect these kinds of incompatibilities/breakages also in the future.

Fixed in Karibu-Testing 1.0.1

**Comment by eiswind** [comment]
That was quick!
