### ISSUE TITLE
GridKt._clickItem does not trigger SelectionListener

### ISSUE THREAD

**Issue by simasch** [mvysny/karibu-testing#96]
I have a grid with a SelectionListener

    grid.addSelectionListener(event -> event.getFirstSelectedItem()
            .ifPresent(seriesRecord -> UI.getCurrent().navigate(SeriesView.class, "" + seriesRecord.getId())));

Now I try to test this 

    GridKt._clickItem(seriesGrid, 0);

But the event is not triggered.

**Comment by mvysny** [comment]
The docs for `_clickItem()` mention that only the `ItemClickEvent` event is fired.

However, if the Grid itself fires a `SelectionEvent` along with `ItemClickEvent` upon item clicking, then it would make sense for Karibu-Testing to do the same. Can you please verify that Grid (in single select mode) fires both events?

**Comment by simasch** [comment]
Yes the Grid fires a SelectionEvent and a ItemClickEvent.

I often use the SelectionListener because the code in the listener should also run when I programmatically select an item

**Comment by mvysny** [comment]
You're right! I can observe the selection events fired *before* item click events (at least on Vaadin 21.0.9). However, this really depends on the selection mode:

* SelectionMode.NONE will not allow you to specify the selection listener at all (an exception is thrown if you try); if the grid is using `SelectionMode.NONE` no SelectionEvents should be fired.
* In multi-select mode, clicking the item only produces Itemclick event, no Selection event is fired. When the selection column is clicked, only the SelectionEvent is fired, no ItemClick event is fired. Therefore, if the Grid is in multi-select mode, no SelectionEvents should be fired.
* In single-select mode, clicking the item produces the SelectionEvent followed by the ItemClickEvent. The contents of the SelectionEvent depends on the current selection though:
   * If no item is selected before clicking, the clicked item is selected.
   * If the item being clicked is selected, the selection is cleared.
   * If some other item is selected, the clicked item is selected. Karibu-Testing will therefore emulate this behavior.
